---
- name: Setup Yandex Server
  hosts: yandex_servers
  become: yes
  gather_facts: no
  tasks:
    - name: Wait for SSH to become ready
      wait_for_connection:
        timeout: 300
        delay: 10

    - name: Gather facts manually
      setup:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
